baseURL: https://convivialist-computer.club/
languageCode: fr-fr
title: Convivialist Computer Club
defaultContentLanguage: fr
theme: hugo-flex

params:
  color: teal           # Any color in CSS syntax
  width: 62rem          # Any length in CSS syntax
  footer: >-            # A hardcoded space is needed before each html element
    Sauf indication contraire, le contenu de ce site fait l'objet d'une licence en vertu de la &#32;
    <a href="http://creativecommons.org/licenses/by/4.0/" rel="license">Creative
    Commons Attribution 4.0 International License</a>.
  rss: Pour vous abonner à ce flux RSS, copiez son adresse et collez-la dans votre lecteur de flux préféré.
  summaries: false      # Set to true to show summaries of posts on homepage
  divider: \a0          # Set to false to remove divider below posts on homepage
  schema: false         # Set to true to add Schema.org metadata
  opengraph: false      # Set to true to add Open Graph metadata
  twittercards: false   # Set to true to add Twitter Cards metadata
  utterances:
    repo:               # Set to Utterances repo URL to add Utterances comments
    issueterm: pathname
    theme: github-light
  netlify:
    honeypot: false     # Set to true to add honeypot field in contact form
    recaptcha: false    # Set to true to add recaptcha challenge in contact form
  # css:                # Uncomment to add custom CSS from a list of files
  #   - css/foo.css
  #   - bar.css
  # js:                 # Uncomment to add custom JS from a list of files
  #   - js/foo.js
  #   - bar.js


menu:
  nav:
  - name: Réseaux sociaux décentralisés
    url: reseaux-sociaux-decentralises/
    weight: 1
  - name: L'atelier
    url: atelier/
    weight: 2
  - name: A propos
    url: a-propos/
    weight: 3
