baseURL: https://convivialist.cc/
languageCode: fr-fr
title: Convivialist Computer Club
defaultContentLanguage: fr
theme: digitalgarden

params:
  enableSearch: false
  description: Le site du Convivialiste Computer Club

menu:
  main:
    - name: Accueil
      url: /
      weight: 1
    - name: Le club
      params:
        header: true
      weight: 2
    - name: Le fédiverse
      url: /fediverse
      weight: 4
    - name: L'atelier
      url: /atelier
      weight: 3
    - name: Pourquoi pas ?
      url: /incubateur
      weight: 5
    - name: Les rencontres
      url: /rencontres
      weight: 6
    - name: A propos
      url: /a-propos
      weight: 7
    - name: Les projets
      params:
        header: true
      weight: 8
    - name: Le Convivialist Music Club
      url: /projets/convivialist-music-club
      weight: 9
    - name: Le Scanner à fanzines
      url: /projets/scanner-a-fanzines
      weight: 10
  social:
    - name: GitHub
      url: "https://github.com/Convivialist-Computer-Club"
      weight: 3
    - name: Email
      url: "mailto:user@example.org"
      weight: 2
    - name: RSS
      url: /rencontres/index.xml
      weight: 1
markup:
  highlight:
    style: dracula
  goldmark:
    renderer:
      unsafe: true
